name: manual-assign
on:
  workflow_dispatch:
    inputs:
      className:
        description: "Class name"
        required: true
        default: "obwodowy"
        type: choice
        options:
          - Obwodowy
          - Pound
jobs:
  assign_for_class:
    name: assign_for_class
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      LOGIN_URL: ${{ secrets.LOGIN_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Prepare Playwright env
        run: |
          bun install
          PLAYWRIGHT_VERSION=1.49.1
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright browser binaries
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/ms-playwright"
          key: "${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}"
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browser binaries & OS dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: |
          npx playwright install chromium --with-deps

      - name: Assign for classes
        run: bun index.ts "${{ inputs.className }}"
